leaderElection:
  enabled: false

# Name of the kcp kubeconfig Secret in the hosting cluster's kcp namespace
kcpKubeconfig: "kcp-init-agent-kubeconfig"

# The "home" workspace for the init-agent
configWorkspace: "root:init-agent"

configCluster:
  rbacSubject:
    kind: User
    name: admin # matches your token auth admin user

wstCluster:
  rbacSubject:
    kind: User
    name: admin # same identity

replicas: 1
