externalHostname: "kcp.example.com"
externalPort: "443"
etcd:
  enabled: false
kcp:
  replicas: 1
  etcd:
    serverAddress: "https://etcd.etcd.svc.cluster.local:2379"
  leaderElection:
    enabled: false
  tokenAuth:
    enabled: true
    fileName: auth-token.csv
    config: |
      admin-token,admin,5555-5555-5555-5555,"system:kcp:admin"
      wf-admin-token,wf-admin,1111-1111-1111-1111,"workspace:workflow-admin"
      wf-user-token,wf-user,2222-2222-2222-2222,"workspace:workflow-user"
  hostAliases:
    enabled: true
    values:
      - ip: "10.103.169.95"
        hostnames:
          - "kcp.example.com"
kcpFrontProxy:
  replicas: 1
  service:
    type: ClusterIP
    port: 443
certificates:
  privateKeys:
    algorithm: RSA
    size: 2048
  dnsNames:
    - localhost
    - "kcp.example.com" # <-- match your externalHostname
