apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v1.sampleworkflows.workflows.com
spec:
  group: workflows.com #API group that serve resource. User write apiVersion: example.com/v1alpha1
  names:
    kind: SampleWorkflow
    listKind: SampleWorkflowList
    plural: sampleworkflows
    singular: sampleworkflow
  scope: Cluster
  versions:
    - name: v1alpha1 # Second part of apiVersion: example.com/v1alpha1
      served: true # Set an old version to served: false after migrating everyone to a newer version.
      storage: true # Only one version can be storage: true
      schema: # OpenAPI v3 schema that validates user input.
        description: "Workflow definition"
        type: object
        properties:
          spec:
            type: object
            properties:
              description:
                type: string
              steps:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
            required:
              - steps
      subresources:
        status: {}
---
apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: sample-workflows # Used in APIBinding definition
spec:
  resources:
    - group: workflows.com # Must match schema's spec.group in APIResourceSchema
      name: sampleworkflows # Must match schema's spec.names.plural
      schema: v1.sampleworkflows.workflows.com # must match schema's metadata.name
      storage:
        crd: {}
